### ISSUE TITLE
Compatibility with GitHub Actions?

### ISSUE THREAD

**Issue by amustill** [ffraenz/private-composer-installer#40]
Has anyone successfully used this package with GitHub Actions? It appears to be as if environment variables are not ready correctly, resulting in failed deployments.

I'm attempting to use the [`php-actions/composer`](https://github.com/php-actions/composer) action, but however I set the environment variable I am constantly facing `Can't resolve placeholder {%ACF_PRO_KEY}. Environment variable 'ACF_PRO_KEY' is not set.` errors.

```
- name: Install dependencies
  uses: php-actions/composer@v5
  with:
    php_version: '7.4'
  env:
    ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}
```

Configuring the `ACF_PRO_KEY` environment variable globally or even hard coding the value instead of using a secret doesn't work. I have an [open issue](https://github.com/php-actions/composer/issues/40) on the `php-actions/composer` repository but the author has confirming the configuration is correct.

Could this be related to how GitHub Actions exposes environment variables and this package reads them? For at the moment they do not appear to be compatible.

**Comment by szepeviktor** [comment]
`php-actions/composer` runs a Docker container so your environment variable does not reach that.

Try simply running Composer

```yaml
      - name: "Install dependencies with Composer"
        env:
          ACF_PRO_KEY: "${{ secrets.ACF_PRO_KEY }}"
        run: "composer update --no-interaction --no-progress"
```

**Comment by amustill** [comment]
Thanks for the response @szepeviktor.

This is my first attempt at using GitHub Actions (coming from GitLab CI) so apologise if I'm incorrect, but my understanding of the [documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv) is that passing the `env` config to step will set it within it? Additionally the author of `php-actions/composer` suggest this is also correct.

For the time being I have found a solution by adding an additional step before `php-actions/composer` which dumps my global `ACF_PRO_KEY` in to an `.env` file. This installs the package without issue.

```
- name: Create .env
  run: |
    echo "ACF_PRO_KEY=$ACF_PRO_KEY" > .env

- name: Install dependencies
  uses: php-actions/composer@v5
  with:
    php_version: '7.4'
```

Would this not counter your argument of the environment variable not being accessible to the Docker container?

I'm not _entirely_ comfortable with this as a solution, but at the moment it appears to be the only way to get `ffraenz/private-composer-installer` and `php-actions/composer` to play nicely with each other.
